/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (C) 2013~2023 Synaptics Incorporated. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 or
 * later as published by the Free Software Foundation.
 *
 * INFORMATION CONTAINED IN THIS DOCUMENT IS PROVIDED "AS-IS," AND
 * SYNAPTICS EXPRESSLY DISCLAIMS ALL EXPRESS AND IMPLIED WARRANTIES,
 * INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE, AND ANY WARRANTIES OF NON-INFRINGEMENT OF ANY
 * INTELLECTUAL PROPERTY RIGHTS. IN NO EVENT SHALL SYNAPTICS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR
 * CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE
 * OF THE INFORMATION CONTAINED IN THIS DOCUMENT, HOWEVER CAUSED AND
 * BASED ON ANY THEORY OF LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, AND EVEN IF SYNAPTICS WAS
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. IF A TRIBUNAL OF
 * COMPETENT JURISDICTION DOES NOT PERMIT THE DISCLAIMER OF DIRECT
 * DAMAGES OR ANY OTHER DAMAGES, SYNAPTICS' TOTAL CUMULATIVE LIABILITY
 * TO ANY PARTY SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS.
 */
#ifndef __SM_APB_GPIO_DEFS_H__
#define __SM_APB_GPIO_DEFS_H__

/* only gpio0 on dolphin */
/* please take care of the definition if there are more GPIO group */
#define APB_GPIO_BASE(x)	(SM_SM_APB_GPIO0_BASE)

#define GPIO_SWPORTA_DR_OFFSET    0x00
#define GPIO_SWPORTA_DDR_OFFSET   0x04
#define GPIO_SWPORTA_CTL_OFFSET   0x08
#define GPIO_INTEN_OFFSET         0x30
#define GPIO_INTMASK_OFFSET       0x34
#define GPIO_INTTYPE_LEVEL_OFFSET 0x38
#define GPIO_INT_POLARITY_OFFSET  0x3C
#define GPIO_INTSTATUS_OFFSET     0x40
#define GPIO_RAW_INTSTATUS_OFFSET 0x44
#define GPIO_DEBOUNCE_OFFSET      0x48
#define GPIO_PORTA_EOI_OFFSET     0x4C
#define GPIO_EXT_PORTA_OFFSET     0x50
#define GPIO_LS_SYNC_OFFSET       0x60
#define GPIO_ID_CODE_OFFSET       0x64
#define GPIO_VER_ID_CODE_OFFSET   0x6C

#define GPIO_CONFIGID_REG2_OFFSET 0x70

#define GPIO_CONFIGID_REG1_OFFSET 0x74

#define GPIO_VERSION_ID_OFFSET    0x78

#define GPIO_PERIPH_ID_OFFSET     0x7C

#define GPIO_SWPORTA_DR(x)       (APB_GPIO_BASE(x) + GPIO_SWPORTA_DR_OFFSET)
#define GPIO_SWPORTA_DDR(x)      (APB_GPIO_BASE(x) + GPIO_SWPORTA_DDR_OFFSET)
#define GPIO_SWPORTA_CTL(x)      (APB_GPIO_BASE(x) + GPIO_SWPORTA_CTL_OFFSET)
#define GPIO_INTEN(x)            (APB_GPIO_BASE(x) + GPIO_INTEN_OFFSET)
#define GPIO_INTMASK(x)          (APB_GPIO_BASE(x) + GPIO_INTMASK_OFFSET)
#define GPIO_INTTYPE_LEVEL(x)    (APB_GPIO_BASE(x) + GPIO_INTTYPE_LEVEL_OFFSET)
#define GPIO_INT_POLARITY(x)     (APB_GPIO_BASE(x) + GPIO_INT_POLARITY_OFFSET)
#define GPIO_INTSTATUS(x)        (APB_GPIO_BASE(x) + GPIO_INTSTATUS_OFFSET)
#define GPIO_RAW_INTSTATUS(x)    (APB_GPIO_BASE(x) + GPIO_RAW_INTSTATUS_OFFSET)
#define GPIO_DEBOUNCE(x)         (APB_GPIO_BASE(x) + GPIO_DEBOUNCE_OFFSET)
#define GPIO_PORTA_EOI(x)        (APB_GPIO_BASE(x) + GPIO_PORTA_EOI_OFFSET)
#define GPIO_EXT_PORTA(x)        (APB_GPIO_BASE(x) + GPIO_EXT_PORTA_OFFSET)
#define GPIO_LS_SYNC(x)          (APB_GPIO_BASE(x) + GPIO_LS_SYNC_OFFSET)
#define GPIO_ID_CODE(x)          (APB_GPIO_BASE(x) + GPIO_ID_CODE_OFFSET)
#define GPIO_VER_ID_CODE(x)      (APB_GPIO_BASE(x) + GPIO_VER_ID_CODE_OFFSET)

#define GPIO_CONFIGID_REG2(x)    (APB_GPIO_BASE(x) + GPIO_CONFIGID_REG2_OFFSET)

#define GPIO_CONFIGID_REG1(x)    (APB_GPIO_BASE(x) + GPIO_CONFIGID_REG1_OFFSET)

#define GPIO_VERSION_ID(x)       (APB_GPIO_BASE(x) + GPIO_VERSION_ID_OFFSET)

#define GPIO_PERIPH_ID(x)        (APB_GPIO_BASE(x) + GPIO_PERIPH_ID_OFFSET)

#endif	//#define __SM_APB_GPIO_DEFS_H__
