/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (C) 2013~2023 Synaptics Incorporated. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 or
 * later as published by the Free Software Foundation.
 *
 * INFORMATION CONTAINED IN THIS DOCUMENT IS PROVIDED "AS-IS," AND
 * SYNAPTICS EXPRESSLY DISCLAIMS ALL EXPRESS AND IMPLIED WARRANTIES,
 * INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE, AND ANY WARRANTIES OF NON-INFRINGEMENT OF ANY
 * INTELLECTUAL PROPERTY RIGHTS. IN NO EVENT SHALL SYNAPTICS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR
 * CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE
 * OF THE INFORMATION CONTAINED IN THIS DOCUMENT, HOWEVER CAUSED AND
 * BASED ON ANY THEORY OF LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, AND EVEN IF SYNAPTICS WAS
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. IF A TRIBUNAL OF
 * COMPETENT JURISDICTION DOES NOT PERMIT THE DISCLAIMER OF DIRECT
 * DAMAGES OR ANY OTHER DAMAGES, SYNAPTICS' TOTAL CUMULATIVE LIABILITY
 * TO ANY PARTY SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS.
 */
#ifndef __SM_APB_ICTL_DEFS_H__
#define __SM_APB_ICTL_DEFS_H__

#define APB_ICTL_BASE	SM_SM_APB_ICTL0_BASE
#define APB_ICTL1_BASE	SM_SM_APB_ICTL1_BASE
#define APB_ICTL2_BASE	SM_SM_APB_ICTL2_BASE

#define ICTL_IRQ_INTEN_OFFSET          0x000
#define ICTL_IRQ_INTEN_OFFSET_L        0x000
#define ICTL_IRQ_INTEN_OFFSET_H        0x004
#define ICTL_IRQ_INTMASK_OFFSET        0x008
#define ICTL_IRQ_INTMASK_OFFSET_L      0x008
#define ICTL_IRQ_INTMASK_OFFSET_H      0x00c
#define ICTL_IRQ_INTFORCE_OFFSET       0x010
#define ICTL_IRQ_INTFORCE_OFFSET_L     0x010
#define ICTL_IRQ_INTFORCE_OFFSET_H     0x014
#define ICTL_IRQ_RAWSTATUS_OFFSET      0x018
#define ICTL_IRQ_RAWSTATUS_OFFSET_L    0x018
#define ICTL_IRQ_RAWSTATUS_OFFSET_H    0x01c
#define ICTL_IRQ_STATUS_OFFSET         0x020
#define ICTL_IRQ_STATUS_OFFSET_L       0x020
#define ICTL_IRQ_STATUS_OFFSET_H       0x024
#define ICTL_IRQ_MASKSTATUS_OFFSET     0x028
#define ICTL_IRQ_MASKSTATUS_OFFSET_L   0x028
#define ICTL_IRQ_MASKSTATUS_OFFSET_H   0x02c
#define ICTL_IRQ_FINALSTATUS_OFFSET    0x030
#define ICTL_IRQ_FINALSTATUS_OFFSET_L  0x030
#define ICTL_IRQ_FINALSTATUS_OFFSET_H  0x034
#define ICTL_IRQ_VECTOR_OFFSET         0x038
#define ICTL_IRQ_VECTOR_OFFSET_L       0x038
#define ICTL_IRQ_VECTOR_OFFSET_H       0x03c
#define ICTL_IRQ_VECTOR_OFFSET_0       0x040
#define ICTL_IRQ_VECTOR_OFFSET_0_L     0x040
#define ICTL_IRQ_VECTOR_OFFSET_0_H     0x044
#define ICTL_IRQ_VECTOR_OFFSET_1       0x048
#define ICTL_IRQ_VECTOR_OFFSET_1_L     0x048
#define ICTL_IRQ_VECTOR_OFFSET_1_H     0x04c
#define ICTL_IRQ_VECTOR_OFFSET_2       0x050
#define ICTL_IRQ_VECTOR_OFFSET_2_L     0x050
#define ICTL_IRQ_VECTOR_OFFSET_2_H     0x054
#define ICTL_IRQ_VECTOR_OFFSET_3       0x058
#define ICTL_IRQ_VECTOR_OFFSET_3_L     0x058
#define ICTL_IRQ_VECTOR_OFFSET_3_H     0x05c
#define ICTL_IRQ_VECTOR_OFFSET_4       0x060
#define ICTL_IRQ_VECTOR_OFFSET_4_L     0x060
#define ICTL_IRQ_VECTOR_OFFSET_4_H     0x064
#define ICTL_IRQ_VECTOR_OFFSET_5       0x068
#define ICTL_IRQ_VECTOR_OFFSET_5_L     0x068
#define ICTL_IRQ_VECTOR_OFFSET_5_H     0x06c
#define ICTL_IRQ_VECTOR_OFFSET_6       0x070
#define ICTL_IRQ_VECTOR_OFFSET_6_L     0x070
#define ICTL_IRQ_VECTOR_OFFSET_6_H     0x074
#define ICTL_IRQ_VECTOR_OFFSET_7       0x078
#define ICTL_IRQ_VECTOR_OFFSET_7_L     0x078
#define ICTL_IRQ_VECTOR_OFFSET_7_H     0x07c
#define ICTL_IRQ_VECTOR_OFFSET_8       0x080
#define ICTL_IRQ_VECTOR_OFFSET_8_L     0x080
#define ICTL_IRQ_VECTOR_OFFSET_8_H     0x084
#define ICTL_IRQ_VECTOR_OFFSET_9       0x088
#define ICTL_IRQ_VECTOR_OFFSET_9_L     0x088
#define ICTL_IRQ_VECTOR_OFFSET_9_H     0x08c
#define ICTL_IRQ_VECTOR_OFFSET_10      0x090
#define ICTL_IRQ_VECTOR_OFFSET_10_L    0x090
#define ICTL_IRQ_VECTOR_OFFSET_10_H    0x094
#define ICTL_IRQ_VECTOR_OFFSET_11      0x098
#define ICTL_IRQ_VECTOR_OFFSET_11_L    0x098
#define ICTL_IRQ_VECTOR_OFFSET_11_H    0x09c
#define ICTL_IRQ_VECTOR_OFFSET_12      0x0a0
#define ICTL_IRQ_VECTOR_OFFSET_12_L    0x0a0
#define ICTL_IRQ_VECTOR_OFFSET_12_H    0x0a4
#define ICTL_IRQ_VECTOR_OFFSET_13      0x0a8
#define ICTL_IRQ_VECTOR_OFFSET_13_L    0x0a8
#define ICTL_IRQ_VECTOR_OFFSET_13_H    0x0ac
#define ICTL_IRQ_VECTOR_OFFSET_14      0x0b0
#define ICTL_IRQ_VECTOR_OFFSET_14_L    0x0b0
#define ICTL_IRQ_VECTOR_OFFSET_14_H    0x0b4
#define ICTL_IRQ_VECTOR_OFFSET_15      0x0b8
#define ICTL_IRQ_VECTOR_OFFSET_15_L    0x0b8
#define ICTL_IRQ_VECTOR_OFFSET_15_H    0x0bc
#define ICTL_FIQ_INTEN_OFFSET          0x0c0
#define ICTL_FIQ_INTMASK_OFFSET        0x0c4
#define ICTL_FIQ_INTFORCE_OFFSET       0x0c8
#define ICTL_FIQ_RAWSTATUS_OFFSET      0x0cc
#define ICTL_FIQ_STATUS_OFFSET         0x0d0
#define ICTL_FIQ_FINALSTATUS_OFFSET    0x0d4
#define ICTL_IRQ_PLEVEL_OFFSET         0x0d8
#define ICTL_ICTL_VERSION_ID_OFFSET    0x0e0
#define ICTL_IRQ_P0_OFFSET             0x0e8
#define ICTL_IRQ_P1_OFFSET             0x0ec
#define ICTL_IRQ_P2_OFFSET             0x0f0
#define ICTL_IRQ_P3_OFFSET             0x0f4
#define ICTL_IRQ_P4_OFFSET             0x0f8
#define ICTL_IRQ_P5_OFFSET             0x0fc
#define ICTL_IRQ_P6_OFFSET             0x100
#define ICTL_IRQ_P7_OFFSET             0x104
#define ICTL_IRQ_P8_OFFSET             0x108
#define ICTL_IRQ_P9_OFFSET             0x10c
#define ICTL_IRQ_P10_OFFSET            0x110
#define ICTL_IRQ_P11_OFFSET            0x114
#define ICTL_IRQ_P12_OFFSET            0x118
#define ICTL_IRQ_P13_OFFSET            0x11c
#define ICTL_IRQ_P14_OFFSET            0x120
#define ICTL_IRQ_P15_OFFSET            0x124
#define ICTL_IRQ_P16_OFFSET            0x128
#define ICTL_IRQ_P17_OFFSET            0x12c
#define ICTL_IRQ_P18_OFFSET            0x130
#define ICTL_IRQ_P19_OFFSET            0x134
#define ICTL_IRQ_P20_OFFSET            0x138
#define ICTL_IRQ_P21_OFFSET            0x13c
#define ICTL_IRQ_P22_OFFSET            0x140
#define ICTL_IRQ_P23_OFFSET            0x144
#define ICTL_IRQ_P24_OFFSET            0x148
#define ICTL_IRQ_P25_OFFSET            0x14c
#define ICTL_IRQ_P26_OFFSET            0x150
#define ICTL_IRQ_P27_OFFSET            0x154
#define ICTL_IRQ_P28_OFFSET            0x158
#define ICTL_IRQ_P29_OFFSET            0x15c
#define ICTL_IRQ_P30_OFFSET            0x160
#define ICTL_IRQ_P31_OFFSET            0x164
#define ICTL_IRQ_P32_OFFSET            0x168
#define ICTL_IRQ_P33_OFFSET            0x16c
#define ICTL_IRQ_P34_OFFSET            0x170
#define ICTL_IRQ_P35_OFFSET            0x174
#define ICTL_IRQ_P36_OFFSET            0x178
#define ICTL_IRQ_P37_OFFSET            0x17c
#define ICTL_IRQ_P38_OFFSET            0x180
#define ICTL_IRQ_P39_OFFSET            0x184
#define ICTL_IRQ_P40_OFFSET            0x188
#define ICTL_IRQ_P41_OFFSET            0x18c
#define ICTL_IRQ_P42_OFFSET            0x190
#define ICTL_IRQ_P43_OFFSET            0x194
#define ICTL_IRQ_P44_OFFSET            0x198
#define ICTL_IRQ_P45_OFFSET            0x19c
#define ICTL_IRQ_P46_OFFSET            0x1a0
#define ICTL_IRQ_P47_OFFSET            0x1a4
#define ICTL_IRQ_P48_OFFSET            0x1a8
#define ICTL_IRQ_P49_OFFSET            0x1ac
#define ICTL_IRQ_P50_OFFSET            0x1b0
#define ICTL_IRQ_P51_OFFSET            0x1b4
#define ICTL_IRQ_P52_OFFSET            0x1b8
#define ICTL_IRQ_P53_OFFSET            0x1bc
#define ICTL_IRQ_P54_OFFSET            0x1c0
#define ICTL_IRQ_P55_OFFSET            0x1c4
#define ICTL_IRQ_P56_OFFSET            0x1c8
#define ICTL_IRQ_P57_OFFSET            0x1cc
#define ICTL_IRQ_P58_OFFSET            0x1d0
#define ICTL_IRQ_P59_OFFSET            0x1d4
#define ICTL_IRQ_P60_OFFSET            0x1d8
#define ICTL_IRQ_P61_OFFSET            0x1dc
#define ICTL_IRQ_P62_OFFSET            0x1e0
#define ICTL_IRQ_P63_OFFSET            0x1e4

#define ICTL_VERSION_ID_WIDTH 32

#ifdef QUICKSTART_APB_ICTL
#define ICTL_IRQ_INTEN          (APB_ICTL_BASE + ICTL_IRQ_INTEN_OFFSET)
#define ICTL_IRQ_INTEN_L        (APB_ICTL_BASE + ICTL_IRQ_INTEN_OFFSET_L)
#define ICTL_IRQ_INTEN_H        (APB_ICTL_BASE + ICTL_IRQ_INTEN_OFFSET_H)
#define ICTL_IRQ_INTMASK        (APB_ICTL_BASE + ICTL_IRQ_INTMASK_OFFSET)
#define ICTL_IRQ_INTMASK_L      (APB_ICTL_BASE + ICTL_IRQ_INTMASK_OFFSET_L)
#define ICTL_IRQ_INTMASK_H      (APB_ICTL_BASE + ICTL_IRQ_INTMASK_OFFSET_H)
#define ICTL_IRQ_INTFORCE       (APB_ICTL_BASE + ICTL_IRQ_INTFORCE_OFFSET)
#define ICTL_IRQ_INTFORCE_L     (APB_ICTL_BASE + ICTL_IRQ_INTFORCE_OFFSET_L)
#define ICTL_IRQ_INTFORCE_H     (APB_ICTL_BASE + ICTL_IRQ_INTFORCE_OFFSET_H)
#define ICTL_IRQ_RAWSTATUS      (APB_ICTL_BASE + ICTL_IRQ_RAWSTATUS_OFFSET)
#define ICTL_IRQ_RAWSTATUS_L    (APB_ICTL_BASE + ICTL_IRQ_RAWSTATUS_OFFSET_L)
#define ICTL_IRQ_RAWSTATUS_H    (APB_ICTL_BASE + ICTL_IRQ_RAWSTATUS_OFFSET_H)
#define ICTL_IRQ_STATUS         (APB_ICTL_BASE + ICTL_IRQ_STATUS_OFFSET)
#define ICTL_IRQ_STATUS_L       (APB_ICTL_BASE + ICTL_IRQ_STATUS_OFFSET_L)
#define ICTL_IRQ_STATUS_H       (APB_ICTL_BASE + ICTL_IRQ_STATUS_OFFSET_H)
#define ICTL_IRQ_MASKSTATUS     (APB_ICTL_BASE + ICTL_IRQ_MASKSTATUS_OFFSET)
#define ICTL_IRQ_MASKSTATUS_L   (APB_ICTL_BASE + ICTL_IRQ_MASKSTATUS_OFFSET_L)
#define ICTL_IRQ_MASKSTATUS_H   (APB_ICTL_BASE + ICTL_IRQ_MASKSTATUS_OFFSET_H)
#define ICTL_IRQ_FINALSTATUS    (APB_ICTL_BASE + ICTL_IRQ_FINALSTATUS_OFFSET)
#define ICTL_IRQ_FINALSTATUS_L  (APB_ICTL_BASE + ICTL_IRQ_FINALSTATUS_OFFSET_L)
#define ICTL_IRQ_FINALSTATUS_H  (APB_ICTL_BASE + ICTL_IRQ_FINALSTATUS_OFFSET_H)
#define ICTL_IRQ_VECTOR         (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET)
#define ICTL_IRQ_VECTOR_L       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_L)
#define ICTL_IRQ_VECTOR_H       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_H)
#define ICTL_IRQ_VECTOR_0       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_0)
#define ICTL_IRQ_VECTOR_0_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_0_L)
#define ICTL_IRQ_VECTOR_0_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_0_H)
#define ICTL_IRQ_VECTOR_1       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_1)
#define ICTL_IRQ_VECTOR_1_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_1_L)
#define ICTL_IRQ_VECTOR_1_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_1_H)
#define ICTL_IRQ_VECTOR_2       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_2)
#define ICTL_IRQ_VECTOR_2_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_2_L)
#define ICTL_IRQ_VECTOR_2_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_2_H)
#define ICTL_IRQ_VECTOR_3       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_3)
#define ICTL_IRQ_VECTOR_3_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_3_L)
#define ICTL_IRQ_VECTOR_3_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_3_H)
#define ICTL_IRQ_VECTOR_4       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_4)
#define ICTL_IRQ_VECTOR_4_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_4_L)
#define ICTL_IRQ_VECTOR_4_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_4_H)
#define ICTL_IRQ_VECTOR_5       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_5)
#define ICTL_IRQ_VECTOR_5_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_5_L)
#define ICTL_IRQ_VECTOR_5_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_5_H)
#define ICTL_IRQ_VECTOR_6       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_6)
#define ICTL_IRQ_VECTOR_6_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_6_L)
#define ICTL_IRQ_VECTOR_6_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_6_H)
#define ICTL_IRQ_VECTOR_7       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_7)
#define ICTL_IRQ_VECTOR_7_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_7_L)
#define ICTL_IRQ_VECTOR_7_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_7_H)
#define ICTL_IRQ_VECTOR_8       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_8)
#define ICTL_IRQ_VECTOR_8_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_8_L)
#define ICTL_IRQ_VECTOR_8_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_8_H)
#define ICTL_IRQ_VECTOR_9       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_9)
#define ICTL_IRQ_VECTOR_9_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_9_L)
#define ICTL_IRQ_VECTOR_9_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_9_H)
#define ICTL_IRQ_VECTOR_10      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_10)
#define ICTL_IRQ_VECTOR_10_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_10_L)
#define ICTL_IRQ_VECTOR_10_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_10_H)
#define ICTL_IRQ_VECTOR_11      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_11)
#define ICTL_IRQ_VECTOR_11_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_11_L)
#define ICTL_IRQ_VECTOR_11_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_11_H)
#define ICTL_IRQ_VECTOR_12      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_12)
#define ICTL_IRQ_VECTOR_12_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_12_L)
#define ICTL_IRQ_VECTOR_12_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_12_H)
#define ICTL_IRQ_VECTOR_13      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_13)
#define ICTL_IRQ_VECTOR_13_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_13_L)
#define ICTL_IRQ_VECTOR_13_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_13_H)
#define ICTL_IRQ_VECTOR_14      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_14)
#define ICTL_IRQ_VECTOR_14_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_14_L)
#define ICTL_IRQ_VECTOR_14_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_14_H)
#define ICTL_IRQ_VECTOR_15      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_15)
#define ICTL_IRQ_VECTOR_15_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_15_L)
#define ICTL_IRQ_VECTOR_15_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_15_H)
#define ICTL_FIQ_INTEN          (APB_ICTL_BASE + ICTL_FIQ_INTEN_OFFSET)
#define ICTL_FIQ_INTMASK        (APB_ICTL_BASE + ICTL_FIQ_INTMASK_OFFSET)
#define ICTL_FIQ_INTFORCE       (APB_ICTL_BASE + ICTL_FIQ_INTFORCE_OFFSET)
#define ICTL_FIQ_RAWSTATUS      (APB_ICTL_BASE + ICTL_FIQ_RAWSTATUS_OFFSET)
#define ICTL_FIQ_STATUS         (APB_ICTL_BASE + ICTL_FIQ_STATUS_OFFSET)
#define ICTL_FIQ_FINALSTATUS    (APB_ICTL_BASE + ICTL_FIQ_FINALSTATUS_OFFSET)
#define ICTL_IRQ_PLEVEL         (APB_ICTL_BASE + ICTL_IRQ_PLEVEL_OFFSET)
#define ICTL_ICTL_VERSION_ID    (APB_ICTL_BASE + ICTL_ICTL_VERSION_ID_OFFSET)
#define ICTL_IRQ_P0_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P0_OFFSET)
#define ICTL_IRQ_P1_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P1_OFFSET)
#define ICTL_IRQ_P2_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P2_OFFSET)
#define ICTL_IRQ_P3_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P3_OFFSET)
#define ICTL_IRQ_P4_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P4_OFFSET)
#define ICTL_IRQ_P5_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P5_OFFSET)
#define ICTL_IRQ_P6_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P6_OFFSET)
#define ICTL_IRQ_P7_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P7_OFFSET)
#define ICTL_IRQ_P8_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P8_OFFSET)
#define ICTL_IRQ_P9_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P9_OFFSET)
#define ICTL_IRQ_P10_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P10_OFFSET)
#define ICTL_IRQ_P11_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P11_OFFSET)
#define ICTL_IRQ_P12_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P12_OFFSET)
#define ICTL_IRQ_P13_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P13_OFFSET)
#define ICTL_IRQ_P14_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P14_OFFSET)
#define ICTL_IRQ_P15_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P15_OFFSET)
#define ICTL_IRQ_P16_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P16_OFFSET)
#define ICTL_IRQ_P17_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P17_OFFSET)
#define ICTL_IRQ_P18_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P18_OFFSET)
#define ICTL_IRQ_P19_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P19_OFFSET)
#define ICTL_IRQ_P20_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P20_OFFSET)
#define ICTL_IRQ_P21_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P21_OFFSET)
#define ICTL_IRQ_P22_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P22_OFFSET)
#define ICTL_IRQ_P23_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P23_OFFSET)
#define ICTL_IRQ_P24_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P24_OFFSET)
#define ICTL_IRQ_P25_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P25_OFFSET)
#define ICTL_IRQ_P26_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P26_OFFSET)
#define ICTL_IRQ_P27_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P27_OFFSET)
#define ICTL_IRQ_P28_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P28_OFFSET)
#define ICTL_IRQ_P29_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P29_OFFSET)
#define ICTL_IRQ_P29_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P29_OFFSET)
#define ICTL_IRQ_P30_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P30_OFFSET)
#define ICTL_IRQ_P31_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P31_OFFSET)
#define ICTL_IRQ_P32_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P32_OFFSET)
#define ICTL_IRQ_P33_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P33_OFFSET)
#define ICTL_IRQ_P34_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P34_OFFSET)
#define ICTL_IRQ_P35_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P35_OFFSET)
#define ICTL_IRQ_P36_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P36_OFFSET)
#define ICTL_IRQ_P37_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P37_OFFSET)
#define ICTL_IRQ_P38_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P38_OFFSET)
#define ICTL_IRQ_P39_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P39_OFFSET)
#define ICTL_IRQ_P40_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P40_OFFSET)
#define ICTL_IRQ_P41_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P41_OFFSET)
#define ICTL_IRQ_P42_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P42_OFFSET)
#define ICTL_IRQ_P43_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P43_OFFSET)
#define ICTL_IRQ_P44_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P44_OFFSET)
#define ICTL_IRQ_P45_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P45_OFFSET)
#define ICTL_IRQ_P46_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P46_OFFSET)
#define ICTL_IRQ_P47_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P47_OFFSET)
#define ICTL_IRQ_P48_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P48_OFFSET)
#define ICTL_IRQ_P49_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P49_OFFSET)
#define ICTL_IRQ_P50_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P50_OFFSET)
#define ICTL_IRQ_P51_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P51_OFFSET)
#define ICTL_IRQ_P52_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P52_OFFSET)
#define ICTL_IRQ_P53_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P53_OFFSET)
#define ICTL_IRQ_P54_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P54_OFFSET)
#define ICTL_IRQ_P55_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P55_OFFSET)
#define ICTL_IRQ_P56_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P56_OFFSET)
#define ICTL_IRQ_P57_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P57_OFFSET)
#define ICTL_IRQ_P58_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P58_OFFSET)
#define ICTL_IRQ_P59_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P59_OFFSET)
#define ICTL_IRQ_P60_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P60_OFFSET)
#define ICTL_IRQ_P61_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P61_OFFSET)
#define ICTL_IRQ_P62_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P62_OFFSET)
#define ICTL_IRQ_P63_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P63_OFFSET)
#endif

#define APB_ICTL_IRQ_INTEN          (APB_ICTL_BASE + ICTL_IRQ_INTEN_OFFSET)
#define APB_ICTL_IRQ_INTEN_L        (APB_ICTL_BASE + ICTL_IRQ_INTEN_OFFSET_L)
#define APB_ICTL_IRQ_INTEN_H        (APB_ICTL_BASE + ICTL_IRQ_INTEN_OFFSET_H)
#define APB_ICTL_IRQ_INTMASK        (APB_ICTL_BASE + ICTL_IRQ_INTMASK_OFFSET)
#define APB_ICTL_IRQ_INTMASK_L      (APB_ICTL_BASE + ICTL_IRQ_INTMASK_OFFSET_L)
#define APB_ICTL_IRQ_INTMASK_H      (APB_ICTL_BASE + ICTL_IRQ_INTMASK_OFFSET_H)
#define APB_ICTL_IRQ_INTFORCE       (APB_ICTL_BASE + ICTL_IRQ_INTFORCE_OFFSET)
#define APB_ICTL_IRQ_INTFORCE_L     (APB_ICTL_BASE + ICTL_IRQ_INTFORCE_OFFSET_L)
#define APB_ICTL_IRQ_INTFORCE_H     (APB_ICTL_BASE + ICTL_IRQ_INTFORCE_OFFSET_H)
#define APB_ICTL_IRQ_RAWSTATUS      (APB_ICTL_BASE + ICTL_IRQ_RAWSTATUS_OFFSET)
#define APB_ICTL_IRQ_RAWSTATUS_L    (APB_ICTL_BASE + ICTL_IRQ_RAWSTATUS_OFFSET_L)
#define APB_ICTL_IRQ_RAWSTATUS_H    (APB_ICTL_BASE + ICTL_IRQ_RAWSTATUS_OFFSET_H)
#define APB_ICTL_IRQ_STATUS         (APB_ICTL_BASE + ICTL_IRQ_STATUS_OFFSET)
#define APB_ICTL_IRQ_STATUS_L       (APB_ICTL_BASE + ICTL_IRQ_STATUS_OFFSET_L)
#define APB_ICTL_IRQ_STATUS_H       (APB_ICTL_BASE + ICTL_IRQ_STATUS_OFFSET_H)
#define APB_ICTL_IRQ_MASKSTATUS     (APB_ICTL_BASE + ICTL_IRQ_MASKSTATUS_OFFSET)
#define APB_ICTL_IRQ_MASKSTATUS_L   (APB_ICTL_BASE + ICTL_IRQ_MASKSTATUS_OFFSET_L)
#define APB_ICTL_IRQ_MASKSTATUS_H   (APB_ICTL_BASE + ICTL_IRQ_MASKSTATUS_OFFSET_H)
#define APB_ICTL_IRQ_FINALSTATUS    (APB_ICTL_BASE + ICTL_IRQ_FINALSTATUS_OFFSET)
#define APB_ICTL_IRQ_FINALSTATUS_L  (APB_ICTL_BASE + ICTL_IRQ_FINALSTATUS_OFFSET_L)
#define APB_ICTL_IRQ_FINALSTATUS_H  (APB_ICTL_BASE + ICTL_IRQ_FINALSTATUS_OFFSET_H)
#define APB_ICTL_IRQ_VECTOR         (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET)
#define APB_ICTL_IRQ_VECTOR_L       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_L)
#define APB_ICTL_IRQ_VECTOR_H       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_H)
#define APB_ICTL_IRQ_VECTOR_0       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_0)
#define APB_ICTL_IRQ_VECTOR_0_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_0_L)
#define APB_ICTL_IRQ_VECTOR_0_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_0_H)
#define APB_ICTL_IRQ_VECTOR_1       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_1)
#define APB_ICTL_IRQ_VECTOR_1_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_1_L)
#define APB_ICTL_IRQ_VECTOR_1_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_1_H)
#define APB_ICTL_IRQ_VECTOR_2       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_2)
#define APB_ICTL_IRQ_VECTOR_2_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_2_L)
#define APB_ICTL_IRQ_VECTOR_2_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_2_H)
#define APB_ICTL_IRQ_VECTOR_3       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_3)
#define APB_ICTL_IRQ_VECTOR_3_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_3_L)
#define APB_ICTL_IRQ_VECTOR_3_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_3_H)
#define APB_ICTL_IRQ_VECTOR_4       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_4)
#define APB_ICTL_IRQ_VECTOR_4_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_4_L)
#define APB_ICTL_IRQ_VECTOR_4_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_4_H)
#define APB_ICTL_IRQ_VECTOR_5       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_5)
#define APB_ICTL_IRQ_VECTOR_5_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_5_L)
#define APB_ICTL_IRQ_VECTOR_5_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_5_H)
#define APB_ICTL_IRQ_VECTOR_6       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_6)
#define APB_ICTL_IRQ_VECTOR_6_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_6_L)
#define APB_ICTL_IRQ_VECTOR_6_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_6_H)
#define APB_ICTL_IRQ_VECTOR_7       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_7)
#define APB_ICTL_IRQ_VECTOR_7_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_7_L)
#define APB_ICTL_IRQ_VECTOR_7_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_7_H)
#define APB_ICTL_IRQ_VECTOR_8       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_8)
#define APB_ICTL_IRQ_VECTOR_8_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_8_L)
#define APB_ICTL_IRQ_VECTOR_8_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_8_H)
#define APB_ICTL_IRQ_VECTOR_9       (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_9)
#define APB_ICTL_IRQ_VECTOR_9_L     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_9_L)
#define APB_ICTL_IRQ_VECTOR_9_H     (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_9_H)
#define APB_ICTL_IRQ_VECTOR_10      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_10)
#define APB_ICTL_IRQ_VECTOR_10_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_10_L)
#define APB_ICTL_IRQ_VECTOR_10_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_10_H)
#define APB_ICTL_IRQ_VECTOR_11      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_11)
#define APB_ICTL_IRQ_VECTOR_11_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_11_L)
#define APB_ICTL_IRQ_VECTOR_11_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_11_H)
#define APB_ICTL_IRQ_VECTOR_12      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_12)
#define APB_ICTL_IRQ_VECTOR_12_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_12_L)
#define APB_ICTL_IRQ_VECTOR_12_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_12_H)
#define APB_ICTL_IRQ_VECTOR_13      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_13)
#define APB_ICTL_IRQ_VECTOR_13_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_13_L)
#define APB_ICTL_IRQ_VECTOR_13_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_13_H)
#define APB_ICTL_IRQ_VECTOR_14      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_14)
#define APB_ICTL_IRQ_VECTOR_14_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_14_L)
#define APB_ICTL_IRQ_VECTOR_14_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_14_H)
#define APB_ICTL_IRQ_VECTOR_15      (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_15)
#define APB_ICTL_IRQ_VECTOR_15_L    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_15_L)
#define APB_ICTL_IRQ_VECTOR_15_H    (APB_ICTL_BASE + ICTL_IRQ_VECTOR_OFFSET_15_H)
#define APB_ICTL_FIQ_INTEN          (APB_ICTL_BASE + ICTL_FIQ_INTEN_OFFSET)
#define APB_ICTL_FIQ_INTMASK        (APB_ICTL_BASE + ICTL_FIQ_INTMASK_OFFSET)
#define APB_ICTL_FIQ_INTFORCE       (APB_ICTL_BASE + ICTL_FIQ_INTFORCE_OFFSET)
#define APB_ICTL_FIQ_RAWSTATUS      (APB_ICTL_BASE + ICTL_FIQ_RAWSTATUS_OFFSET)
#define APB_ICTL_FIQ_STATUS         (APB_ICTL_BASE + ICTL_FIQ_STATUS_OFFSET)
#define APB_ICTL_FIQ_FINALSTATUS    (APB_ICTL_BASE + ICTL_FIQ_FINALSTATUS_OFFSET)
#define APB_ICTL_IRQ_PLEVEL         (APB_ICTL_BASE + ICTL_IRQ_PLEVEL_OFFSET)
#define APB_ICTL_ICTL_VERSION_ID    (APB_ICTL_BASE + ICTL_ICTL_VERSION_ID_OFFSET)
#define APB_ICTL_IRQ_P0_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P0_OFFSET)
#define APB_ICTL_IRQ_P1_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P1_OFFSET)
#define APB_ICTL_IRQ_P2_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P2_OFFSET)
#define APB_ICTL_IRQ_P3_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P3_OFFSET)
#define APB_ICTL_IRQ_P4_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P4_OFFSET)
#define APB_ICTL_IRQ_P5_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P5_OFFSET)
#define APB_ICTL_IRQ_P6_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P6_OFFSET)
#define APB_ICTL_IRQ_P7_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P7_OFFSET)
#define APB_ICTL_IRQ_P8_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P8_OFFSET)
#define APB_ICTL_IRQ_P9_ADDR        (APB_ICTL_BASE + ICTL_IRQ_P9_OFFSET)
#define APB_ICTL_IRQ_P10_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P10_OFFSET)
#define APB_ICTL_IRQ_P11_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P11_OFFSET)
#define APB_ICTL_IRQ_P12_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P12_OFFSET)
#define APB_ICTL_IRQ_P13_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P13_OFFSET)
#define APB_ICTL_IRQ_P14_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P14_OFFSET)
#define APB_ICTL_IRQ_P15_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P15_OFFSET)
#define APB_ICTL_IRQ_P16_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P16_OFFSET)
#define APB_ICTL_IRQ_P17_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P17_OFFSET)
#define APB_ICTL_IRQ_P18_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P18_OFFSET)
#define APB_ICTL_IRQ_P19_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P19_OFFSET)
#define APB_ICTL_IRQ_P20_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P20_OFFSET)
#define APB_ICTL_IRQ_P21_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P21_OFFSET)
#define APB_ICTL_IRQ_P22_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P22_OFFSET)
#define APB_ICTL_IRQ_P23_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P23_OFFSET)
#define APB_ICTL_IRQ_P24_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P24_OFFSET)
#define APB_ICTL_IRQ_P25_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P25_OFFSET)
#define APB_ICTL_IRQ_P26_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P26_OFFSET)
#define APB_ICTL_IRQ_P27_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P27_OFFSET)
#define APB_ICTL_IRQ_P28_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P28_OFFSET)
#define APB_ICTL_IRQ_P29_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P29_OFFSET)
#define APB_ICTL_IRQ_P29_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P29_OFFSET)
#define APB_ICTL_IRQ_P30_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P30_OFFSET)
#define APB_ICTL_IRQ_P31_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P31_OFFSET)
#define APB_ICTL_IRQ_P32_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P32_OFFSET)
#define APB_ICTL_IRQ_P33_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P33_OFFSET)
#define APB_ICTL_IRQ_P34_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P34_OFFSET)
#define APB_ICTL_IRQ_P35_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P35_OFFSET)
#define APB_ICTL_IRQ_P36_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P36_OFFSET)
#define APB_ICTL_IRQ_P37_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P37_OFFSET)
#define APB_ICTL_IRQ_P38_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P38_OFFSET)
#define APB_ICTL_IRQ_P39_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P39_OFFSET)
#define APB_ICTL_IRQ_P40_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P40_OFFSET)
#define APB_ICTL_IRQ_P41_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P41_OFFSET)
#define APB_ICTL_IRQ_P42_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P42_OFFSET)
#define APB_ICTL_IRQ_P43_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P43_OFFSET)
#define APB_ICTL_IRQ_P44_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P44_OFFSET)
#define APB_ICTL_IRQ_P45_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P45_OFFSET)
#define APB_ICTL_IRQ_P46_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P46_OFFSET)
#define APB_ICTL_IRQ_P47_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P47_OFFSET)
#define APB_ICTL_IRQ_P48_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P48_OFFSET)
#define APB_ICTL_IRQ_P49_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P49_OFFSET)
#define APB_ICTL_IRQ_P50_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P50_OFFSET)
#define APB_ICTL_IRQ_P51_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P51_OFFSET)
#define APB_ICTL_IRQ_P52_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P52_OFFSET)
#define APB_ICTL_IRQ_P53_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P53_OFFSET)
#define APB_ICTL_IRQ_P54_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P54_OFFSET)
#define APB_ICTL_IRQ_P55_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P55_OFFSET)
#define APB_ICTL_IRQ_P56_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P56_OFFSET)
#define APB_ICTL_IRQ_P57_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P57_OFFSET)
#define APB_ICTL_IRQ_P58_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P58_OFFSET)
#define APB_ICTL_IRQ_P59_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P59_OFFSET)
#define APB_ICTL_IRQ_P60_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P60_OFFSET)
#define APB_ICTL_IRQ_P61_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P61_OFFSET)
#define APB_ICTL_IRQ_P62_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P62_OFFSET)
#define APB_ICTL_IRQ_P63_ADDR       (APB_ICTL_BASE + ICTL_IRQ_P63_OFFSET)

#endif	//#define __SM_APB_ICTL_DEFS_H__
