/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (C) 2013~2023 Synaptics Incorporated. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 or
 * later as published by the Free Software Foundation.
 *
 * INFORMATION CONTAINED IN THIS DOCUMENT IS PROVIDED "AS-IS," AND
 * SYNAPTICS EXPRESSLY DISCLAIMS ALL EXPRESS AND IMPLIED WARRANTIES,
 * INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE, AND ANY WARRANTIES OF NON-INFRINGEMENT OF ANY
 * INTELLECTUAL PROPERTY RIGHTS. IN NO EVENT SHALL SYNAPTICS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR
 * CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE
 * OF THE INFORMATION CONTAINED IN THIS DOCUMENT, HOWEVER CAUSED AND
 * BASED ON ANY THEORY OF LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, AND EVEN IF SYNAPTICS WAS
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. IF A TRIBUNAL OF
 * COMPETENT JURISDICTION DOES NOT PERMIT THE DISCLAIMER OF DIRECT
 * DAMAGES OR ANY OTHER DAMAGES, SYNAPTICS' TOTAL CUMULATIVE LIABILITY
 * TO ANY PARTY SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS.
 */

#ifndef _SM_MEM_MAP_ITCM_H
#define _SM_MEM_MAP_ITCM_H

/*ITCM last 4K(0x1000) for queue ram*/
#define RAM_MSGQ_SIZE	(0x1000)
#define SM_TCM_QRAM_BASE (SM_MEMMAP_ITCM_BASE + SM_MEMMAP_ITCM_SIZE - RAM_MSGQ_SIZE)

/** RAM TS layout*/
#define RAM_TS_MAX_SIZE		(0x200)
#define SM_RAM_TS_BASE	(SM_TCM_QRAM_BASE - RAM_TS_MAX_SIZE)
#define SM_REBOOTREASON_ADDR (SM_TCM_QRAM_BASE - RAM_TS_MAX_SIZE)

/** ATF reboot reason parameter*/
#define SM_ATF_REBOOT_PARAM_OFFSET (0x400)
#define SM_ATF_REBOOT_PARAM_ADDR (SM_TCM_QRAM_BASE - SM_ATF_REBOOT_PARAM_OFFSET)
#define SM_ATF_REBOOT_PARAM_SIZE 0x04


#endif
