/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (C) 2013~2023 Synaptics Incorporated. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 or
 * later as published by the Free Software Foundation.
 *
 * INFORMATION CONTAINED IN THIS DOCUMENT IS PROVIDED "AS-IS," AND
 * SYNAPTICS EXPRESSLY DISCLAIMS ALL EXPRESS AND IMPLIED WARRANTIES,
 * INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE, AND ANY WARRANTIES OF NON-INFRINGEMENT OF ANY
 * INTELLECTUAL PROPERTY RIGHTS. IN NO EVENT SHALL SYNAPTICS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR
 * CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE
 * OF THE INFORMATION CONTAINED IN THIS DOCUMENT, HOWEVER CAUSED AND
 * BASED ON ANY THEORY OF LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, AND EVEN IF SYNAPTICS WAS
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. IF A TRIBUNAL OF
 * COMPETENT JURISDICTION DOES NOT PERMIT THE DISCLAIMER OF DIRECT
 * DAMAGES OR ANY OTHER DAMAGES, SYNAPTICS' TOTAL CUMULATIVE LIABILITY
 * TO ANY PARTY SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS.
 */
#ifdef IRENABLE
#ifdef XMP_PROTOCAL
#ifndef __IR_XMP_H__
#define __IR_XMP_H__

/*Xfinity XR11 Remote*/
#define VENDOR_ID_XFINITY 0x170F443E

/*TIMING VALUES FOR CLIP XMP1 PROTO for 33% data cycle*/
#define XMP_HEADER_MIN_HIGH_TIME ((972-68)*SM_SYSTEM_HZ)	//22866  //22866.25
#define XMP_HEADER_MAX_HIGH_TIME ((972+68+15*137)*SM_SYSTEM_HZ) //76891  //76890.75
//((1038.33 + (15 * 136.71) - 13.02) * SYSTEM_HZ)

#define XMP_HEADER_699_TICKS_IN_US (699*1.085*SM_SYSTEM_HZ)
#define XMP_HEADER_126_TICKS_IN_US (126*1.085*SM_SYSTEM_HZ)

#define FRAME_CYCLE_NORMAL_MAX	6225730
#define FRAME_CYCLE_FIRSTHOLD_MAX (6225730/2)
#define HoldKeySkipTime 3

UINT32 read_xmp(UINT32*, UINT32*, UINT32*, BOOL*);

#endif
#endif
#endif
